config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: "posts#index"
  constraints(ClientDomainConstraint.new) do
    resources :posts do
      resources :comments, except: :show
    end
    resources :top_ups, only: [:new, :create]
  end
  resources :categories
  get '/:unique_id', to: 'posts#short_url'

  constraints(AdminDomainConstraint.new) do
    namespace :admin do
      resources :users
      resources :posts
    end
  end

  namespace :api do
    resources :regions, only: :index, defaults: { format: :json } do
      resources :provinces, only: :index, defaults: { format: :json } do
        resources :cities_municipalities, only: :index, defaults: { format: :json } do
          resources :barangays, only: :index, defaults: { format: :json }
        end
      end
      resources :districts, only: :index, defaults: { format: :json } do
        resources :cities_municipalities, only: :index, defaults: { format: :json } do
          resources :barangays, only: :index, defaults: { format: :json }
        end
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :post, counter_cache: true
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :validate_comment_owner, only: [:edit, :update, :destroy]

  def index
    @comments = @post.comments
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(params_comment)
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(params[:post_id])
    else
      render :new
    end
  end

  def edit ;end

  def update
    if @comment.update(params_comment)
      redirect_to post_path(params[:post_id])
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(params[:post_id])
  end

  private
  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def params_comment
    params.require(:comment)
          .permit(:content)
          .merge(post_id: params[:post_id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def validate_comment_owner
    unless @comment.user == current_user
      flash[:notice] = 'the comment not belongs to you'
      redirect_to post_comments_path(@post)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with model: comment, url: path, data: { turbo: false } do |form| %>
  <div class="form-group">
    <%= form.label 'Write new comment' %>
    <%= form.text_area :content, class: "form-control my-2", placeholder: "New Comment", required: true %>
  </div>
  <%= form.submit class: "btn btn-success" %>
<% end %>

app/views/comments/edit.html.erb
<div class="container">
  <div class="card shadow-sm mb-10 bg-white rounded">
    <h1 class="text-center card-header bg-dark text-white"><%= @post.title %></h1>
    <div class="container">
      <div class="card-body">
        <h3>Edit Comment</h3>
        <%= render partial: 'form', locals: { comment: @comment, path: post_comment_path(@post, @comment) } %>

        <%= link_to 'Back', post_path(params[:post_id]), class: "bi-arrow-left" %>
      </div>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<!--<h1>Title: <%#= @post.title %></h1>-->
<!--<h2>Comments</h2>-->
<!--<ul>-->
  <%# @comments.each do |comment| %>
<!--  <li><%#= comment.content %> (<%#= comment.created_at %>)-->
    <%#= link_to 'Edit', edit_post_comment_path(@post, comment) if comment.user == current_user %>
<!--    <%#= button_to 'Delete', post_comment_path(@post, comment), method: :delete if comment.user == current_user%></li>-->
    <%# end %>
<!--</ul>-->
<%#= link_to 'New', new_post_comment_path %>
<!--<br>-->
<%#= link_to "Post List", posts_path %>

app/views/comments/new.html.erb
<!--<h1>Title: <%#= @post.title %></h1>-->
<!--<h2>New Comment</h2>-->
<%#= render partial: 'form', locals:  {post: @post, comment: @comment, path: post_comments_path(@post)} %>