config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: "posts#index"
  constraints(ClientDomainConstraint.new) do
    resources :posts do
      resources :comments, except: :show
    end
    resources :top_ups, only: [:new, :create]
  end
  resources :categories
  get '/:unique_id', to: 'posts#short_url'

  constraints(AdminDomainConstraint.new) do
    namespace :admin do
      resources :users
      resources :posts
    end
  end

  namespace :api do
    resources :regions, only: :index, defaults: { format: :json } do
      resources :provinces, only: :index, defaults: { format: :json } do
        resources :cities_municipalities, only: :index, defaults: { format: :json } do
          resources :barangays, only: :index, defaults: { format: :json }
        end
      end
      resources :districts, only: :index, defaults: { format: :json } do
        resources :cities_municipalities, only: :index, defaults: { format: :json } do
          resources :barangays, only: :index, defaults: { format: :json }
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Discard::Model
  validates :title, presence: true
  validates :content, presence: true
  after_validation :generate_short_string
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :comments
  has_many :post_category_ships
  has_many :categories, through: :post_category_ships
  has_one :post_count_preview
  belongs_to :region, class_name: 'Address::Region', foreign_key: 'address_region_id'
  belongs_to :province, class_name: 'Address::Province', foreign_key: 'address_province_id'

  private

  def generate_short_string
    loop do
      @unique_string = sprintf "%04d", rand(2 - 9999)
      break unless Post.exists?(unique_id: @unique_string)
    end
    self.unique_id = @unique_string
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  def index
    @posts = Post.includes(:user, :categories, :region, :province).order(comments_count: :desc).kept.page(params[:page]).per(7)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # before_action :validate_post_owner, only: [:edit, :update, :destroy]
  require 'csv'

  def index
    @posts = Post.includes(:user, :categories, :region, :province).order(comments_count: :desc).kept.page(params[:page]).per(7)
    @hot_posts = Post.order(comments_count: :desc).limit(3).select { |post| post.comments_count >= 1 }
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts, each_serializer: PostSerializer }
      format.csv {
        csv_string = CSV.generate do |csv|
          csv << [User.human_attribute_name(:email), Post.human_attribute_name(:id), Post.human_attribute_name(:title), Post.human_attribute_name(:content), Post.human_attribute_name(:categories), Post.human_attribute_name(:created_at)]
          @posts.each do |p|
            csv << [p.user.email, p.id, p.title, p.content, p.categories.pluck(:disaster).join(','), p.created_at]
          end
        end
        render plain: csv_string
      }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if Rails.env.development?
      @post.ip_address = Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
    else
      @post.ip_address = request.remote_ip
    end
    if @post.save
      flash[:notice] = 'The post was successfully saved'
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @post, serializer: PostSerializer }
    end
  end

  def edit
    authorize @post, :edit?, policy_class: PostPolicy
  end

  def update
    authorize @post, :update?, policy_class: PostPolicy
    if @post.update(post_params)
      flash[:notice] = 'The post is up to date'
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    authorize @post, :destroy?, policy_class: PostPolicy
    if @post.comments_count >= 1
      flash[:notice] = "The post with comments can't be deleted."
    else
      @post.discard
      flash[:notice] = "The post was successfully deleted."
    end
    redirect_to posts_path
  end

  def short_url
    # route_list = RouteList.find_by(unique_id: params[:unique_id])
    # unique_num
    # post = Post.find_by unique_id: 8998
    # redirect_to action: "show", id: post.id
    @post = Post.find_by(unique_id: params[:unique_id])
    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :address, :unique_id, :image, :address_region_id, :address_province_id, category_ids: [])
  end

  # def validate_post_owner
  #   unless @post.user == current_user
  #     flash[:notice] = 'This post not belongs to you'
  #     redirect_to posts_path
  #   end
  # end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<article>
  <% @post.comments.each do |comment| %>
    <div style="display: flex; flex-direction: row; align-items: center">
      <div>
        <small class="text-muted"><%= comment.user.email %> </small>
        <p class=""><%= comment.content %></p>
      </div>
      <div style="display: flex; flex-direction: row;">
        <%= link_to 'Edit', edit_post_comment_path(@post, comment), class: "btn btn-outline-success m-2" if comment.user == current_user %>
        <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete, :onclick => "return confirm('Are you sure you want to delete?')", class: "btn btn-outline-danger m-2" if comment.user == current_user %>
      </div>
    </div>
    <small><%= comment.created_at %></small>
    <hr>
  <% end %>
</article>

app/views/posts/_form.html.erb
<div class="container">
  <%= form_with model: @post, data: { controller: :location } do |form| %>
    <% if @post.errors.any? %>
      <ul>
        <% @post.errors.each do |error| %>
          <li class="text-danger"><%= error.full_message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="form-group">
      <strong><%= form.label :title %></strong>
      <div><%= form.text_field :title, class: "form-control" %></div>
    </div>
    <div class="form-group">
      <strong><%= form.label :content %></strong>
      <div><%= form.text_area :content, class: "form-control", style: "min-height: 25rem; resize: none" %></div>
    </div>

    <div class="m-2">
      <%= form.collection_check_boxes :category_ids, Category.all, :id, :disaster %>
      <%= link_to 'Add types', new_category_path, class: "btn btn-secondary" %>
    </div>

    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :address_region_id %>
      <%= form.collection_select :address_region_id,
                                 Address::Region.all, :id, :name,
                                 { prompt: 'Select region' },
                                 data: { location_target: 'selectedRegionId', action: 'change->location#fetchProvinces' }%>
    </div>

    <div>
      <%= form.label :address_province_id %>
      <%= form.collection_select :address_province_id, [], nil, nil, { prompt: 'Select province' }, data: { location_target: 'selectProvinceId' } %>
    </div>
    <%= form.submit 'Submit', class: "btn btn-success float-end" %>

      <div>
        <%= form.label :address_city_municipality_id %>
        <%= form.collection_select :address_city_municipality_id, [], nil, nil, { prompt: 'Select City/Municipality' }, data: { location_target: 'selectCityMunicipalityId', action: 'change->location#fetchBarangays' }, class: "form-control" %>
      </div>
      <div>
        <%= form.label :address_barangay_id %>
        <%= form.collection_select :address_barangay_id, [], nil, nil, { prompt: 'Select Barangay' }, data: { location_target: 'selectBarangayId' }, class: "form-control" %>
      </div>
    </div>
  <% end %>

app/views/posts/edit.html.erb
<div class="container">
  <%= link_to 'Back', posts_path, class: "bi-arrow-left" %>
  <h2 class="text-center">Edit post</h2>
  <%= render partial: 'form', locals: { post: @post } %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1><%= t("index_h1") %></h1>
  <%= link_to 'Export CSV', posts_path(format: :csv)%>
  <table class="table text-center table-bordered table-striped table-dark">
    <thead class="thead-dark ">
    <tr>
      <th><%= Post.human_attribute_name(:title) %></th>
      <th><%= Post.human_attribute_name(:content) %></th>
      <th><%= Post.human_attribute_name(:address) %></th>
      <th><%= Post.human_attribute_name(:category) %></th>
      <th><%= Post.human_attribute_name(:author) %></th>
      <th><%= Post.human_attribute_name(:comments_count) %></th>
      <th><%= Post.human_attribute_name(:shorten_url) %></th>
      <th><%= Post.human_attribute_name(:ip_address) %></th>
      <th colspan="3"><%= Post.human_attribute_name(:action) %></th>
      <th><%= Post.human_attribute_name(:copy_clipboard) %></th>
    </tr>
    </thead>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= post.title %>
        </td>
        <td><%= post.content %></td>
        <td><%= "#{post.region&.name} #{post.province&.name} #{post.address}" %></td>
        <td><%= post.categories.pluck(:disaster).join(', ') %></td>
        <td><%= post.user.email %></td>
        <td><%= post.comments_count %> <%= image_tag ('hot.png'), width: "30", height: "30" if @hot_posts.include?(post) %></td>
        <td><%= link_to "#{post.unique_id}",post.unique_id %></td>
        <td><%= Geocoder.search(post.ip_address).first.country%></td>
        <td><%= link_to 'Read more', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-primary bi-pencil" if policy(post).edit? %></td>
        <td><%= button_to 'Delete', post_path(post), method: :delete, :onclick => "return confirm('Are you sure you want to delete?')", class: "btn btn-outline-danger bi-trash" if policy(post).destroy? %></td>
        <td data-controller="clipboard">
          <span data-clipboard-target="email"><%= post.user.email %></span>
          <button data-action="click->clipboard#copy">copy</button>
        </td>
      </tr>
    <% end %>
  </table>
  <%= paginate @posts, theme: 'bootstrap-5',
               pagination_class: "pagination-sm flex-wrap justify-content-center",
               nav_class: "d-inline-block" %>
  <div>
    <%= link_to "New", new_post_path, class: "btn btn-success px-4 mb-4 bi-plus float-lg-end" %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= link_to 'Back', posts_path, class: "bi-arrow-left" %>
</div>
<h1 class="text-center">New Disaster Information</h1>
<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/show.html.erb
<div class="container">
  <%= link_to 'Back', posts_path, class: "bi-arrow-left" %>
  <div class="text-center ">
    <%= image_tag @post.image.url, class: "rounded" if @post.image? %>
  </div>

  <h2 class="text-center mt-3"><%= @post.title %></h2>

  <small class="text-muted bi-clock float-lg-end"><%= @post.created_at %></small>

  <div style="font-size: 1.2rem">
    <p><strong>Category: </strong><%= @post.categories.pluck(:disaster).join(', ') %></p>
  </div>
  <div style="font-size: 1.2rem">
    <p class="text-justify"><strong>Content: </strong><%= @post.content %></p>
  </div>
  <div>
    <p><strong>Address: </strong><%= @post.address %></p>
  </div>
  <p><strong>
    <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      Show comments
    </a></strong></p>
  <div class="collapse.show mb-5" id="collapseExample">
    <div class="card card-body">
      <%= render 'posts/comments' %>
      <%= render partial: 'comments/form', locals: { comment: @post.comments.new, path: post_comments_path(@post) } %>
    </div>
  </div>
</div>