config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: "posts#index"
  constraints(ClientDomainConstraint.new) do
    resources :posts do
      resources :comments, except: :show
    end
    resources :top_ups, only: [:new, :create]
  end
  resources :categories
  get '/:unique_id', to: 'posts#short_url'

  constraints(AdminDomainConstraint.new) do
    namespace :admin do
      resources :users
      resources :posts
    end
  end

  namespace :api do
    resources :regions, only: :index, defaults: { format: :json } do
      resources :provinces, only: :index, defaults: { format: :json } do
        resources :cities_municipalities, only: :index, defaults: { format: :json } do
          resources :barangays, only: :index, defaults: { format: :json }
        end
      end
      resources :districts, only: :index, defaults: { format: :json } do
        resources :cities_municipalities, only: :index, defaults: { format: :json } do
          resources :barangays, only: :index, defaults: { format: :json }
        end
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :disaster, presence: true

  has_many :post_category_ships, dependent: :restrict_with_exception
  has_many :posts, through: :post_category_ships
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit ;end

  def update
    if @category.update(params_category)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:disaster)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="container">
  <div class="card-body">
    <%= form_with model: category, url: path, data: { turbo: false } do |form| %>
      <%= form.label :disaster %>
      <%= form.text_field :disaster, class: "form-control mb-4" %>
      <div class="text-center">
        <%= form.submit class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to 'Back', new_post_path %>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="container">
  <div class="card shadow-sm mb-10 bg-white rounded">
    <h1> Category id: <%= @category.id %></h1>
    <%= render partial: 'form', locals: { category: @category, path: category_path(@category) } %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container ">
  <div class="card shadow-sm mb-10 bg-white rounded">
    <h1 class="card-header text-center">Category List</h1>
    <div class="card-body">
      <% @categories.each do |category| %>
        <div class="m-2">
          <ul>
            <li><%= category.disaster %>
              <%= link_to 'Edit', edit_category_path(category) %>
              <%= button_to 'Delete', category_path(category), method: :delete, style: "display:inline" %></li>
          </ul>
        </div>
      <% end %>
      <%= link_to 'New', new_category_path, class: "bi-plus btn btn-success px-4 float-end" %>
    </div>
  </div>
  <%= link_to 'Home', posts_path, class: "bi-house-fill" %>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="card shadow-sm mb-10 bg-white rounded">
    <h4 class="card-header text-center bg-dark text-white">New Category</h4>
    <%= render partial: 'form', locals: { category: @category, path: categories_path } %>
  </div>
</div>